# Generated by Django 2.2.1 on 2019-05-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.FilePathField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('size', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
