# Generated by Django 2.2.1 on 2019-05-06 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DirectoryListing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerepository',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filerepository',
            name='archived_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 6, 15, 22, 16, 154869, tzinfo=utc)),
        ),
    ]
