# Generated by Django 2.2.1 on 2019-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirectoryListing', '0003_auto_20190506_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
