# Generated by Django 2.2.1 on 2019-05-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DirectoryListing', '0006_auto_20190507_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='archived_date',
            field=models.DateTimeField(null=True),
        ),
    ]
